export const meusCoffees = [
    {
        id: 1,
        name: 'Expresso Tradicional',
        price: 990,
        image: '/coffee1.png',
        description: 'O trandicional café feito com água quente e grãos moídos',
        quantity: 0,
    },
    {
        id: 2,
        name: 'Expresso Americano',
        price: 990,
        image: 'coffee2.png',
        description: 'Expresso diluído, menos intenso que o tradicional',
        quantity: 0,
    },
    {
        id: 3,
        name: 'Expresso Cremoso',
        price: 9.90,
        image: '/coffee3.png',
        description: 'Café expresso tradicional com espuma cremosa',
        quantity: 0,
    },
    {
        id: 4,
        name: 'Expresso Gelado',
        price: 990,
        image: '/coffee4.png',
        description: 'Bebida preparada com café expresso e cubos de gelo',
        quantity: 0,
    },
    {
        id: 5,
        name: 'Café com Leite',
        price: 990,
        image: '/coffee5.png',
        description: 'Meio a meio de expresso tradicional com leite vaporizado',
        quantity: 0,
    },
    {
        id: 6,
        name: 'Latte',
        price: 990,
        image: '/coffee6.png',
        description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
        quantity: 0,
    },
    {
        id: 7,
        name: 'Capuccino',
        price: 990,
        image: '/coffee7.png',
        description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
        quantity: 0,
    },
    {
        id: 8,
        name: 'Macchiato',
        price: 990,
        image: '/coffee8.png',
        description: 'Café expresso misturado com um pouco de leite quente e espuma',
        quantity: 0,
    },
    {
        id: 9,
        name: 'Mocaccino',
        price: 990,
        image: '/coffee9.png',
        description: 'Café expresso com calda de chocolate, pouco leite e espuma',
        quantity: 0,
    },
    {
        id: 10,
        name: 'Chocolate Quente',
        price: 990,
        image: '/coffee10.png',
        description: 'Bebida feita com chocolate dissolvido no leite quente e café',
        quantity: 0,
    },
    {
        id: 11,
        name: 'Cubano',
        price: 990,
        image: '/coffee11.png',
        description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
        quantity: 0,
    },
    {
        id: 12,
        name: 'Havaiano',
        price: 990,
        image: '/coffee12.png',
        description: 'Bebida adocicada preparada com café e leite de coco',
        quantity: 0,
    },
    {
        id: 13,
        name: 'Árabe',
        price: 990,
        image: '/coffee13.png',
        description: 'Bebida preparada com grãos de café árabe e especiarias',
        quantity: 0,
    },
    {
        id: 14,
        name: 'Irlandês',
        price: 990,
        image: '/coffee14.png',
        description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
        quantity: 0,
    },
];